from django.urls import path

from . import views

urlpatterns = [path("", views.index, name="index"),
               path("about", views.about, name="about"),
               path("blog", views.blog, name="blog"),
               path("blogDetails", views.blogDetails, name="blogDetails"),
               path("contact", views.contact, name="contact"),
               path("notFound", views.notFound, name="notFound"),
               path("career", views.career, name="career"),
               path("service", views.service, name="service"),
               path("serviceDetails", views.serviceDetails, name="serviceDetails"),
               path("teamDetails", views.teamDetails, name="teamDetails"),
               path("faq", views.faq, name="faq"),
               path("saveInfo", views.saveInfo, name="saveInfo"),
               path("saveEmail", views.saveEmail, name="saveEmail"),
               path("webDevelopement", views.web, name="webDevelopement"),
               path("app", views.app, name="app"),
               path("CC", views.CloudComputing, name="CC"),
               path("ITManaged", views.ITManaged, name="ITManaged"),
               path("SoftwareDevelopment", views.SoftwareDevelopment, name="SoftwareDevelopment"),
               path("Seo", views.Seo, name="Seo"),
            #    path("team", views.team, name="team"),
            #    path("pricing", views.pricing, name="pricing"),
            #    path("productDetails", views.productDetails, name="productDetails"),
            #    path("products", views.products, name="products"),
            #    path("project2", views.project2, name="project2"),
            #    path("service2", views.service2, name="service2"),
               ]