# Generated by Django 4.1.6 on 2023-02-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InfoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('website', models.URLField()),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='info',
        ),
    ]
