# Generated by Django 4.1.6 on 2023-06-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_emailclass_infoclass_delete_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoclass',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='infoclass',
            old_name='firstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='infoclass',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='infoclass',
            old_name='website',
            new_name='Website',
        ),
    ]
